config/routes.rb
Rails.application.routes.draw do
  
  get "/", to: "welcome#index", as: :root

  get "/contato", to: "contact#index", as: :contact

  get "/post", to: "post#log", as: :log
  post "/post", to: "post#confirmation", as: false

  get "/post/new", to: "post#new", as: :new_post
  post "/post/new", to: "post#create", as: false

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index

  end

end

app/controllers/post_controller.rb
class PostController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)

    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(
      :title,
      :description
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @posts = Post.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/index.html.erb
<div class="container">
  
  <%= link_to "https://www.facebook.com/hygor.daniel.18", target: "_blank", class: "contact" do %>
    <%= image_tag "png/facebook29.png" %> 
    <p>FACEBOOK - HYGOR DANIEL</p>
  <% end %>
  
  <%= link_to "https://plus.google.com/110773153646763714085/posts", target: "_blank", class: "contact" do %>
    <%= image_tag "png/plus76.png" %>  
    <p>PLUS - HYGOR DANIEL</p>
  <% end %>

  <%= link_to "https://www.youtube.com/channel/UCalBiDNyB8r4dvWlHT_caKA/feed", target: "_blank", class: "contact" do %>
    <%= image_tag "png/youtube28.png" %> 
    <p>YOUTUBE - HYGOR DANIEL</p>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hygor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <ul>
    <li><%= link_to "HOME", root_path %></li>
    <li><a href="https://www.youtube.com/channel/UCalBiDNyB8r4dvWlHT_caKA/videos" target="_blank">VIDEOS</a></li>
    <li><%= link_to "CONTATO", contact_path %></li>
  </ul>
</nav>

<div class="bg-skin">
</div>

<div class="bg-steve">
</div>

<%= yield %>

</body>
</html>

app/views/post/log.html.erb
<div class="container">
  <%= form_for @log, url: log_path do |log| %>
    <%= label_tag "Nome" %>
    <%= log.text_field :name %>

    <%= label_tag "Senha" %>
    <%= log.text_field :password %>

    <%= log.submit "Iniciar" %>
  <% end %>
</div>

app/views/post/new.html.erb
<div class="container">
  <%= form_for @post, url: new_post_path do |post| %>
    <%= label_tag "Titulo da postagem" %>
    <%= post.text_field :title %><br>

    <%= label_tag "Post" %>
    <%= post.text_area :description %><br>

    <%= post.submit "Enviar" %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="videos">
  <iframe src="//www.youtube.com/embed/b4FfuLmjV1w" frameborder="0" allowfullscreen></iframe>

  <iframe src="//www.youtube.com/embed/sABd_7slMQI" frameborder="0" allowfullscreen></iframe>

  <iframe src="//www.youtube.com/embed/ao27CDTSN3g" frameborder="0" allowfullscreen></iframe>
</div>

<% @posts.reverse.each do |post| %>
  <div class="posts">
  <h1><%= post.title %></h1>
  <p>
    <%= post.description %>
  </p>
</div>  
<% end %>